#!bin/bash
./structure_features.x structures/structures_KG_LF_1 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_2 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_3 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_4 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_5 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_6 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_7 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_8 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_9 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_10 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_11 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_12 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_13 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_14 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_15 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_16 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_17 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_18 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_19 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_20 >> structures/structures_KG_LF_annot
./structure_features.x structures/structures_KG_LF_21 >> structures/structures_KG_LF_annot
