nohup cat seqs/$1_premrna_NES_seqs_00 | $2 > structures/$1_premrna_NES_struct_0 &
nohup cat seqs/$1_premrna_NES_seqs_01 | $2 > structures/$1_premrna_NES_struct_1 &
nohup cat seqs/$1_premrna_NES_seqs_02 | $2 > structures/$1_premrna_NES_struct_2 &
nohup cat seqs/$1_premrna_NES_seqs_03 | $2 > structures/$1_premrna_NES_struct_3 &
nohup cat seqs/$1_premrna_NES_seqs_04 | $2 > structures/$1_premrna_NES_struct_4 &
nohup cat seqs/$1_premrna_NES_seqs_05 | $2 > structures/$1_premrna_NES_struct_5 &
nohup cat seqs/$1_premrna_NES_seqs_06 | $2 > structures/$1_premrna_NES_struct_6 &
nohup cat seqs/$1_premrna_NES_seqs_07 | $2 > structures/$1_premrna_NES_struct_7 &
nohup cat seqs/$1_premrna_NES_seqs_08 | $2 > structures/$1_premrna_NES_struct_8 &
nohup cat seqs/$1_premrna_NES_seqs_09 | $2 > structures/$1_premrna_NES_struct_9 &
nohup cat seqs/$1_premrna_NES_seqs_10 | $2 > structures/$1_premrna_NES_struct_10 &
nohup cat seqs/$1_premrna_NES_seqs_11 | $2 > structures/$1_premrna_NES_struct_11 &
nohup cat seqs/$1_premrna_NES_seqs_12 | $2 > structures/$1_premrna_NES_struct_12 &
nohup cat seqs/$1_premrna_NES_seqs_13 | $2 > structures/$1_premrna_NES_struct_13 &
nohup cat seqs/$1_premrna_NES_seqs_14 | $2 > structures/$1_premrna_NES_struct_14 &
nohup cat seqs/$1_premrna_NES_seqs_15 | $2 > structures/$1_premrna_NES_struct_15 &
nohup cat seqs/$1_premrna_NES_seqs_16 | $2 > structures/$1_premrna_NES_struct_16 &
nohup cat seqs/$1_premrna_NES_seqs_17 | $2 > structures/$1_premrna_NES_struct_17 &
nohup cat seqs/$1_premrna_NES_seqs_18 | $2 > structures/$1_premrna_NES_struct_18 &
nohup cat seqs/$1_premrna_NES_seqs_19 | $2 > structures/$1_premrna_NES_struct_19 
nohup cat seqs/$1_premrna_NES_seqs_20 | $2 > structures/$1_premrna_NES_struct_20 &
nohup cat seqs/$1_premrna_NES_seqs_21 | $2 > structures/$1_premrna_NES_struct_21 &
nohup cat seqs/$1_premrna_NES_seqs_22 | $2 > structures/$1_premrna_NES_struct_22 &
nohup cat seqs/$1_premrna_NES_seqs_23 | $2 > structures/$1_premrna_NES_struct_23 &
nohup cat seqs/$1_premrna_NES_seqs_24 | $2 > structures/$1_premrna_NES_struct_24 &
nohup cat seqs/$1_premrna_NES_seqs_25 | $2 > structures/$1_premrna_NES_struct_25 &
nohup cat seqs/$1_premrna_NES_seqs_26 | $2 > structures/$1_premrna_NES_struct_26 &
nohup cat seqs/$1_premrna_NES_seqs_27 | $2 > structures/$1_premrna_NES_struct_27 &
nohup cat seqs/$1_premrna_NES_seqs_28 | $2 > structures/$1_premrna_NES_struct_28 &
nohup cat seqs/$1_premrna_NES_seqs_29 | $2 > structures/$1_premrna_NES_struct_29 &
nohup cat seqs/$1_premrna_NES_seqs_30 | $2 > structures/$1_premrna_NES_struct_30 &
nohup cat seqs/$1_premrna_NES_seqs_31 | $2 > structures/$1_premrna_NES_struct_31 &
nohup cat seqs/$1_premrna_NES_seqs_32 | $2 > structures/$1_premrna_NES_struct_32 &
nohup cat seqs/$1_premrna_NES_seqs_33 | $2 > structures/$1_premrna_NES_struct_33 &
nohup cat seqs/$1_premrna_NES_seqs_34 | $2 > structures/$1_premrna_NES_struct_34 &
nohup cat seqs/$1_premrna_NES_seqs_35 | $2 > structures/$1_premrna_NES_struct_35 &
nohup cat seqs/$1_premrna_NES_seqs_36 | $2 > structures/$1_premrna_NES_struct_36 &
nohup cat seqs/$1_premrna_NES_seqs_37 | $2 > structures/$1_premrna_NES_struct_37 &
nohup cat seqs/$1_premrna_NES_seqs_38 | $2 > structures/$1_premrna_NES_struct_38 &
nohup cat seqs/$1_premrna_NES_seqs_39 | $2 > structures/$1_premrna_NES_struct_39 
nohup cat seqs/$1_premrna_NES_seqs_40 | $2 > structures/$1_premrna_NES_struct_40 &
nohup cat seqs/$1_premrna_NES_seqs_41 | $2 > structures/$1_premrna_NES_struct_41 &
nohup cat seqs/$1_premrna_NES_seqs_42 | $2 > structures/$1_premrna_NES_struct_42 &
nohup cat seqs/$1_premrna_NES_seqs_43 | $2 > structures/$1_premrna_NES_struct_43 &
nohup cat seqs/$1_premrna_NES_seqs_44 | $2 > structures/$1_premrna_NES_struct_44 &
nohup cat seqs/$1_premrna_NES_seqs_45 | $2 > structures/$1_premrna_NES_struct_45 &
nohup cat seqs/$1_premrna_NES_seqs_46 | $2 > structures/$1_premrna_NES_struct_46 &
nohup cat seqs/$1_premrna_NES_seqs_47 | $2 > structures/$1_premrna_NES_struct_47 &
nohup cat seqs/$1_premrna_NES_seqs_48 | $2 > structures/$1_premrna_NES_struct_48 &
nohup cat seqs/$1_premrna_NES_seqs_49 | $2 > structures/$1_premrna_NES_struct_49 &
nohup cat seqs/$1_premrna_NES_seqs_50 | $2 > structures/$1_premrna_NES_struct_50 &
nohup cat seqs/$1_premrna_NES_seqs_51 | $2 > structures/$1_premrna_NES_struct_51 &
nohup cat seqs/$1_premrna_NES_seqs_52 | $2 > structures/$1_premrna_NES_struct_52 &
nohup cat seqs/$1_premrna_NES_seqs_53 | $2 > structures/$1_premrna_NES_struct_53 &
nohup cat seqs/$1_premrna_NES_seqs_54 | $2 > structures/$1_premrna_NES_struct_54 &
nohup cat seqs/$1_premrna_NES_seqs_55 | $2 > structures/$1_premrna_NES_struct_55 &
nohup cat seqs/$1_premrna_NES_seqs_56 | $2 > structures/$1_premrna_NES_struct_56 &
nohup cat seqs/$1_premrna_NES_seqs_57 | $2 > structures/$1_premrna_NES_struct_57 &
nohup cat seqs/$1_premrna_NES_seqs_58 | $2 > structures/$1_premrna_NES_struct_58 &
nohup cat seqs/$1_premrna_NES_seqs_59 | $2 > structures/$1_premrna_NES_struct_59 &
nohup cat seqs/$1_premrna_NES_seqs_60 | $2 > structures/$1_premrna_NES_struct_60 &
