cat structures/$1_premrna_NES_struct_0 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_1 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_2 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_3 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_4 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_5 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_6 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_7 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_8 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_9 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_10 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_11 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_12 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_13 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_14 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_15 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_16 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_17 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_18 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_19 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_20 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_21 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_22 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_23 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_24 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_25 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_26 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_27 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_28 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_29 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_30 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_31 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_32 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_33 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_34 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_35 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_36 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_37 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_38 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_39 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_40 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_41 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_42 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_43 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_44 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_45 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_46 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_47 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_48 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_49 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_50 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_51 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_52 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_53 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_54 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_55 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_56 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_57 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_58 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_59 >> structures/$1_premrna_NES_struct_all
cat structures/$1_premrna_NES_struct_60 >> structures/$1_premrna_NES_struct_all
