cat structures/$1_premrna_struct_1 > structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_2 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_3 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_4 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_5 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_6 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_7 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_8 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_9 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_10 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_11 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_12 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_13 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_14 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_15 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_16 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_17 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_18 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_19 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_20 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_21 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_22 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_23 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_24 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_25 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_26 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_27 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_28 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_29 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_30 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_31 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_32 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_33 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_34 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_35 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_36 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_37 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_38 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_39 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_40 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_41 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_42 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_43 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_44 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_45 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_46 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_47 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_48 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_49 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_50 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_51 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_52 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_53 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_54 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_55 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_56 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_57 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_58 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_59 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_60 >> structures/$1_premrna_struct_all
cat structures/$1_premrna_struct_61 >> structures/$1_premrna_struct_all
