nohup cat seqs/hg38_premrna_seqs_RS_1.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_1 &
nohup cat seqs/hg38_premrna_seqs_RS_2.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_2 &
nohup cat seqs/hg38_premrna_seqs_RS_3.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_3 &
nohup cat seqs/hg38_premrna_seqs_RS_4.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_4 &
nohup cat seqs/hg38_premrna_seqs_RS_5.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_5 &
nohup cat seqs/hg38_premrna_seqs_RS_6.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_6 &
nohup cat seqs/hg38_premrna_seqs_RS_7.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_7 &
nohup cat seqs/hg38_premrna_seqs_RS_8.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_8 &
nohup cat seqs/hg38_premrna_seqs_RS_9.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_9 &
nohup cat seqs/hg38_premrna_seqs_RS_10.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_10 &
nohup cat seqs/hg38_premrna_seqs_RS_11.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_11 &
nohup cat seqs/hg38_premrna_seqs_RS_12.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_12 &
nohup cat seqs/hg38_premrna_seqs_RS_13.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_13 &
nohup cat seqs/hg38_premrna_seqs_RS_14.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_14 &
nohup cat seqs/hg38_premrna_seqs_RS_15.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_15 &
nohup cat seqs/hg38_premrna_seqs_RS_16.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_16 &
nohup cat seqs/hg38_premrna_seqs_RS_17.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_17 &
nohup cat seqs/hg38_premrna_seqs_RS_18.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_18 &
nohup cat seqs/hg38_premrna_seqs_RS_19.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_19 &
nohup cat seqs/hg38_premrna_seqs_RS_20.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_20 &
nohup cat seqs/hg38_premrna_seqs_RS_21.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_21 &
nohup cat seqs/hg38_premrna_seqs_RS_22.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_22 &
nohup cat seqs/hg38_premrna_seqs_RS_23.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_23 &
nohup cat seqs/hg38_premrna_seqs_RS_24.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_24 &
nohup cat seqs/hg38_premrna_seqs_RS_25.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_25 &
nohup cat seqs/hg38_premrna_seqs_RS_26.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_26 &
nohup cat seqs/hg38_premrna_seqs_RS_27.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_27 &
nohup cat seqs/hg38_premrna_seqs_RS_28.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_28 &
nohup cat seqs/hg38_premrna_seqs_RS_29.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_29 &
nohup cat seqs/hg38_premrna_seqs_RS_30.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_30 &
nohup cat seqs/hg38_premrna_seqs_RS_31.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_31 &
nohup cat seqs/hg38_premrna_seqs_RS_32.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_32 &
nohup cat seqs/hg38_premrna_seqs_RS_33.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_33 &
nohup cat seqs/hg38_premrna_seqs_RS_34.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_34 &
nohup cat seqs/hg38_premrna_seqs_RS_35.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_35 &
nohup cat seqs/hg38_premrna_seqs_RS_36.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_36 &
nohup cat seqs/hg38_premrna_seqs_RS_37.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_37 &
nohup cat seqs/hg38_premrna_seqs_RS_38.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_38 &
nohup cat seqs/hg38_premrna_seqs_RS_39.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_39 &
nohup cat seqs/hg38_premrna_seqs_RS_40.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_40 &
nohup cat seqs/hg38_premrna_seqs_RS_41.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_41 &
nohup cat seqs/hg38_premrna_seqs_RS_42.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_42 &
nohup cat seqs/hg38_premrna_seqs_RS_43.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_43 &
nohup cat seqs/hg38_premrna_seqs_RS_44.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_44 &
nohup cat seqs/hg38_premrna_seqs_RS_45.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_45 &
nohup cat seqs/hg38_premrna_seqs_RS_46.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_46 &
nohup cat seqs/hg38_premrna_seqs_RS_47.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_47 &
nohup cat seqs/hg38_premrna_seqs_RS_48.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_48 &
nohup cat seqs/hg38_premrna_seqs_RS_49.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_49 &
nohup cat seqs/hg38_premrna_seqs_RS_50.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_50 &
nohup cat seqs/hg38_premrna_seqs_RS_51.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_51 &
nohup cat seqs/hg38_premrna_seqs_RS_52.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_52 &
nohup cat seqs/hg38_premrna_seqs_RS_53.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_53 &
nohup cat seqs/hg38_premrna_seqs_RS_54.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_54 &
nohup cat seqs/hg38_premrna_seqs_RS_55.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_55 &
nohup cat seqs/hg38_premrna_seqs_RS_56.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_56 &
nohup cat seqs/hg38_premrna_seqs_RS_57.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_57 &
nohup cat seqs/hg38_premrna_seqs_RS_58.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_58 &
nohup cat seqs/hg38_premrna_seqs_RS_59.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_59 &
nohup cat seqs/hg38_premrna_seqs_RS_60.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_60 &
nohup cat seqs/hg38_premrna_seqs_RS_61.fa | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_struct_RS_61 &