nohup cat seqs/hg38_premrna_NES_seqs_RS_00 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_0 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_01 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_1 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_02 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_2 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_03 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_3 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_04 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_4 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_05 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_5 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_06 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_6 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_07 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_7 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_08 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_8 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_09 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_9 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_10 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_10 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_11 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_11 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_12 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_12 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_13 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_13 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_14 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_14 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_15 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_15 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_16 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_16 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_17 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_17 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_18 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_18 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_19 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_19 
nohup cat seqs/hg38_premrna_NES_seqs_RS_20 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_20 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_21 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_21 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_22 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_22 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_23 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_23 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_24 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_24 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_25 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_25 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_26 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_26 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_27 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_27 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_28 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_28 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_29 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_29 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_30 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_30 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_31 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_31 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_32 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_32 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_33 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_33 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_34 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_34 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_35 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_35 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_36 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_36 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_37 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_37 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_38 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_38 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_39 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_39 
nohup cat seqs/hg38_premrna_NES_seqs_RS_40 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_40 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_41 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_41 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_42 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_42 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_43 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_43 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_44 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_44 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_45 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_45 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_46 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_46 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_47 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_47 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_48 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_48 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_49 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_49 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_50 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_50 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_51 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_51 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_52 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_52 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_53 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_53 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_54 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_54 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_55 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_55 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_56 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_56 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_57 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_57 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_58 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_58 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_59 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_59 &
nohup cat seqs/hg38_premrna_NES_seqs_RS_60 | /usr/local/install/LinearFold/linearfold > structures/hg38_premrna_NES_struct_RS_60 &