nohup cat seqs/$1_premrna_seqs_1.fa | $2 > structures/$1_premrna_struct_1 &
nohup cat seqs/$1_premrna_seqs_2.fa | $2 > structures/$1_premrna_struct_2 &
nohup cat seqs/$1_premrna_seqs_3.fa | $2 > structures/$1_premrna_struct_3 &
nohup cat seqs/$1_premrna_seqs_4.fa | $2 > structures/$1_premrna_struct_4 &
nohup cat seqs/$1_premrna_seqs_5.fa | $2 > structures/$1_premrna_struct_5 &
nohup cat seqs/$1_premrna_seqs_6.fa | $2 > structures/$1_premrna_struct_6 &
nohup cat seqs/$1_premrna_seqs_7.fa | $2 > structures/$1_premrna_struct_7 &
nohup cat seqs/$1_premrna_seqs_8.fa | $2 > structures/$1_premrna_struct_8 &
nohup cat seqs/$1_premrna_seqs_9.fa | $2 > structures/$1_premrna_struct_9 &
nohup cat seqs/$1_premrna_seqs_10.fa | $2 > structures/$1_premrna_struct_10 &
nohup cat seqs/$1_premrna_seqs_11.fa | $2 > structures/$1_premrna_struct_11 &
nohup cat seqs/$1_premrna_seqs_12.fa | $2 > structures/$1_premrna_struct_12 &
nohup cat seqs/$1_premrna_seqs_13.fa | $2 > structures/$1_premrna_struct_13 &
nohup cat seqs/$1_premrna_seqs_14.fa | $2 > structures/$1_premrna_struct_14 &
nohup cat seqs/$1_premrna_seqs_15.fa | $2 > structures/$1_premrna_struct_15 &
nohup cat seqs/$1_premrna_seqs_16.fa | $2 > structures/$1_premrna_struct_16 &
nohup cat seqs/$1_premrna_seqs_17.fa | $2 > structures/$1_premrna_struct_17 &
nohup cat seqs/$1_premrna_seqs_18.fa | $2 > structures/$1_premrna_struct_18 &
nohup cat seqs/$1_premrna_seqs_19.fa | $2 > structures/$1_premrna_struct_19 &
nohup cat seqs/$1_premrna_seqs_20.fa | $2 > structures/$1_premrna_struct_20 &
nohup cat seqs/$1_premrna_seqs_21.fa | $2 > structures/$1_premrna_struct_21 &
nohup cat seqs/$1_premrna_seqs_22.fa | $2 > structures/$1_premrna_struct_22 &
nohup cat seqs/$1_premrna_seqs_23.fa | $2 > structures/$1_premrna_struct_23 &
nohup cat seqs/$1_premrna_seqs_24.fa | $2 > structures/$1_premrna_struct_24 &
nohup cat seqs/$1_premrna_seqs_25.fa | $2 > structures/$1_premrna_struct_25 &
nohup cat seqs/$1_premrna_seqs_26.fa | $2 > structures/$1_premrna_struct_26 &
nohup cat seqs/$1_premrna_seqs_27.fa | $2 > structures/$1_premrna_struct_27 &
nohup cat seqs/$1_premrna_seqs_28.fa | $2 > structures/$1_premrna_struct_28 &
nohup cat seqs/$1_premrna_seqs_29.fa | $2 > structures/$1_premrna_struct_29 &
nohup cat seqs/$1_premrna_seqs_30.fa | $2 > structures/$1_premrna_struct_30 &
nohup cat seqs/$1_premrna_seqs_31.fa | $2 > structures/$1_premrna_struct_31 &
nohup cat seqs/$1_premrna_seqs_32.fa | $2 > structures/$1_premrna_struct_32 &
nohup cat seqs/$1_premrna_seqs_33.fa | $2 > structures/$1_premrna_struct_33 &
nohup cat seqs/$1_premrna_seqs_34.fa | $2 > structures/$1_premrna_struct_34 &
nohup cat seqs/$1_premrna_seqs_35.fa | $2 > structures/$1_premrna_struct_35 &
nohup cat seqs/$1_premrna_seqs_36.fa | $2 > structures/$1_premrna_struct_36 &
nohup cat seqs/$1_premrna_seqs_37.fa | $2 > structures/$1_premrna_struct_37 &
nohup cat seqs/$1_premrna_seqs_38.fa | $2 > structures/$1_premrna_struct_38 &
nohup cat seqs/$1_premrna_seqs_39.fa | $2 > structures/$1_premrna_struct_39 &
nohup cat seqs/$1_premrna_seqs_40.fa | $2 > structures/$1_premrna_struct_40 &
nohup cat seqs/$1_premrna_seqs_41.fa | $2 > structures/$1_premrna_struct_41 &
nohup cat seqs/$1_premrna_seqs_42.fa | $2 > structures/$1_premrna_struct_42 &
nohup cat seqs/$1_premrna_seqs_43.fa | $2 > structures/$1_premrna_struct_43 &
nohup cat seqs/$1_premrna_seqs_44.fa | $2 > structures/$1_premrna_struct_44 &
nohup cat seqs/$1_premrna_seqs_45.fa | $2 > structures/$1_premrna_struct_45 &
nohup cat seqs/$1_premrna_seqs_46.fa | $2 > structures/$1_premrna_struct_46 &
nohup cat seqs/$1_premrna_seqs_47.fa | $2 > structures/$1_premrna_struct_47 &
nohup cat seqs/$1_premrna_seqs_48.fa | $2 > structures/$1_premrna_struct_48 &
nohup cat seqs/$1_premrna_seqs_49.fa | $2 > structures/$1_premrna_struct_49 &
nohup cat seqs/$1_premrna_seqs_50.fa | $2 > structures/$1_premrna_struct_50 &
nohup cat seqs/$1_premrna_seqs_51.fa | $2 > structures/$1_premrna_struct_51 &
nohup cat seqs/$1_premrna_seqs_52.fa | $2 > structures/$1_premrna_struct_52 &
nohup cat seqs/$1_premrna_seqs_53.fa | $2 > structures/$1_premrna_struct_53 &
nohup cat seqs/$1_premrna_seqs_54.fa | $2 > structures/$1_premrna_struct_54 &
nohup cat seqs/$1_premrna_seqs_55.fa | $2 > structures/$1_premrna_struct_55 &
nohup cat seqs/$1_premrna_seqs_56.fa | $2 > structures/$1_premrna_struct_56 &
nohup cat seqs/$1_premrna_seqs_57.fa | $2 > structures/$1_premrna_struct_57 &
nohup cat seqs/$1_premrna_seqs_58.fa | $2 > structures/$1_premrna_struct_58 &
nohup cat seqs/$1_premrna_seqs_59.fa | $2 > structures/$1_premrna_struct_59 &
nohup cat seqs/$1_premrna_seqs_60.fa | $2 > structures/$1_premrna_struct_60 &
nohup cat seqs/$1_premrna_seqs_61.fa | $2 > structures/$1_premrna_struct_61 &
